import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Morgans Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Morgans Portfolio</title>
            <link rel="icon" href="/favicon.ico" />
        </head>
        <body className={inter.className}>{children}</body>
        </html>
    );
}
